# Generated by Django 4.1.2 on 2022-11-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remindermodel",
            name="date",
        ),
        migrations.RemoveField(
            model_name="remindermodel",
            name="time",
        ),
        migrations.AddField(
            model_name="remindermodel",
            name="datetime",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
