# Generated by Django 4.1.2 on 2022-10-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="disease",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="crop",
            name="remedy",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
